[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/info"
  to = "/.netlify/functions/info"
  status = 200

[[redirects]]
  from = "/api/models"
  to = "/.netlify/functions/models"
  status = 200

[[redirects]]
  from = "/api/generations/sync-cloudinary"
  to = "/.netlify/functions/generations-sync-cloudinary"
  status = 200

[[redirects]]
  from = "/api/generations"
  to = "/.netlify/functions/generations"
  status = 200

[[redirects]]
  from = "/api/models/:modelId/apply"
  to = "/.netlify/functions/models-apply"
  status = 200

[[redirects]]
  from = "/api/models/:modelId/status"
  to = "/.netlify/functions/models-status"
  status = 200

[[redirects]]
  from = "/api/models/multi-apply"
  to = "/.netlify/functions/models-multi-apply"
  status = 200

[[redirects]]
  from = "/api/models/:modelId"
  to = "/.netlify/functions/models-delete"
  status = 200

[[redirects]]
  from = "/api/generations/:generationId/status"
  to = "/.netlify/functions/generations-status"
  status = 200

[[redirects]]
  from = "/api/generations/:generationId"
  to = "/.netlify/functions/generations-delete"
  status = 200

[[redirects]]
  from = "/api/blob/generations/save"
  to = "/.netlify/functions/blob-generations-save"
  status = 200

[[redirects]]
  from = "/api/blob/generations/list"
  to = "/.netlify/functions/blob-generations-list"
  status = 200

[[redirects]]
  from = "/api/blob/generations/:generationId"
  to = "/.netlify/functions/blob-generations-delete"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200