import { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Loader2, Image as ImageIcon, CheckCircle } from "lucide-react";

interface GenerationSlot {
  id: string;
  status: 'empty' | 'generating' | 'completed' | 'failed';
  progress: number;
  imageUrl?: string;
  modelName?: string;
  error?: string;
}

interface GenerationSlotsProps {
  generations: any[];
  onSlotClick?: (slotId: string) => void;
}

export function GenerationSlots({ generations, onSlotClick }: GenerationSlotsProps) {
  const [slots, setSlots] = useState<GenerationSlot[]>([
    { id: '1', status: 'empty', progress: 0 },
    { id: '2', status: 'empty', progress: 0 },
    { id: '3', status: 'empty', progress: 0 },
    { id: '4', status: 'empty', progress: 0 }
  ]);

  // Update slots based on latest generations
  useEffect(() => {
    if (generations.length === 0) return;

    const latestGenerations = generations.slice(-4);
    
    setSlots(currentSlots => {
      const newSlots = [...currentSlots];
      
      latestGenerations.forEach((gen, index) => {
        if (newSlots[index]) {
          if (gen.status === 'completed' && gen.outputImageUrl) {
            newSlots[index] = {
              id: gen.id.toString(),
              status: 'completed',
              progress: 100,
              imageUrl: gen.outputImageUrl,
              modelName: gen.modelName
            };
          } else if (gen.status === 'processing') {
            newSlots[index] = {
              id: gen.id.toString(),
              status: 'generating',
              progress: Math.random() * 60 + 20, // Simulate progress
              modelName: gen.modelName
            };
          } else if (gen.status === 'failed') {
            newSlots[index] = {
              id: gen.id.toString(),
              status: 'failed',
              progress: 0,
              modelName: gen.modelName,
              error: gen.errorMessage || 'Generation failed'
            };
          }
        }
      });
      
      return newSlots;
    });
  }, [generations]);

  // Simulate progress for generating slots
  useEffect(() => {
    const interval = setInterval(() => {
      setSlots(currentSlots => 
        currentSlots.map(slot => {
          if (slot.status === 'generating' && slot.progress < 95) {
            return {
              ...slot,
              progress: Math.min(slot.progress + Math.random() * 15, 95)
            };
          }
          return slot;
        })
      );
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const getSlotContent = (slot: GenerationSlot) => {
    switch (slot.status) {
      case 'empty':
        return (
          <div className="flex flex-col items-center justify-center h-full text-muted-foreground">
            <ImageIcon className="h-12 w-12 mb-2 opacity-50" />
            <p className="text-sm text-center">Připraveno na generování</p>
          </div>
        );

      case 'generating':
        return (
          <div className="flex flex-col items-center justify-center h-full p-4">
            <Loader2 className="h-8 w-8 mb-4 animate-spin text-blue-500" />
            <p className="text-sm font-medium mb-2">{slot.modelName}</p>
            <div className="w-full mb-2">
              <Progress value={slot.progress} className="h-2" />
            </div>
            <p className="text-xs text-muted-foreground">
              {Math.round(slot.progress)}% dokončeno
            </p>
          </div>
        );

      case 'completed':
        return (
          <div className="relative h-full group cursor-pointer" onClick={() => onSlotClick?.(slot.id)}>
            <img
              src={slot.imageUrl}
              alt={`Generated by ${slot.modelName}`}
              className="w-full h-full object-cover rounded-lg"
            />
            <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <CheckCircle className="h-8 w-8 text-green-400" />
            </div>
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-3">
              <p className="text-white text-sm font-medium">{slot.modelName}</p>
            </div>
          </div>
        );

      case 'failed':
        return (
          <div className="flex flex-col items-center justify-center h-full text-red-500 p-4">
            <div className="h-12 w-12 rounded-full bg-red-100 flex items-center justify-center mb-2">
              <span className="text-xl">✕</span>
            </div>
            <p className="text-sm font-medium text-center">{slot.modelName}</p>
            <p className="text-xs text-muted-foreground text-center mt-1">
              {slot.error}
            </p>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="grid grid-cols-4 gap-3 w-full">
      {slots.map((slot) => (
        <Card key={slot.id} className="h-48 overflow-hidden hover:shadow-lg transition-shadow">
          {getSlotContent(slot)}
        </Card>
      ))}
    </div>
  );
}